baseURL = "/"
languageCode = "en-us"
title = "Root + Rally"
theme = "kube"
description = "Root + Rally is a platform committed to championing women’s professional sports by showcasing all game information in a central place, making it easy to find and attend games in your area"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Root + Rally" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "myemail@myaddress.xxx"

[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "About"
    weight = -100
    url = "/faq/"
